#!/bin/sh
# intel fpga sdk settings
export ALTERAOCLSDKROOT=/home/pcz/intelFPGA/17.1/hld
export QUARTUS_ROOTDIR_OVERRIDE=/home/pcz/intelFPGA/17.1/quartus

export INTELFPGAOCLSDKROOT=$ALTERAOCLSDKROOT
export AOCL_BOARD_PACKAGE_ROOT=$INTELFPGAOCLSDKROOT/board/s5_ref


export PATH=$INTELFPGAOCLSDKROOT/bin:$PATH
export LD_LIBRARY_PATH=$INTELFPGAOCLSDKROOT/host/linux64/lib
export LD_LIBRARY_PATH=$AOCL_BOARD_PACKAGE_ROOT/linux64/lib:$LD_LIBRARY_PATH

export CL_CONTEXT_EMULATOR_DEVICE_INTELFPGA=1

