/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_pzque_sparkdl_saoclib_nativeapi_NDRangeKernel__ */

#ifndef _Included_com_pzque_sparkdl_saoclib_nativeapi_NDRangeKernel__
#define _Included_com_pzque_sparkdl_saoclib_nativeapi_NDRangeKernel__
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_pzque_sparkdl_saoclib_nativeapi_NDRangeKernel__
 * Method:    newInstance
 * Signature: (I[J[JJJLjava/lang/String;[Ljava/lang/Object;)J
 */
JNIEXPORT jlong JNICALL Java_com_pzque_sparkdl_saoclib_nativeapi_NDRangeKernel_00024_newInstance
        (JNIEnv *, jobject, jlong, jlong, jstring, jobjectArray);

/*
 * Class:     com_pzque_sparkdl_saoclib_nativeapi_NDRangeKernel__
 * Method:    destroyInstance
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_pzque_sparkdl_saoclib_nativeapi_NDRangeKernel_00024_destroyInstance
        (JNIEnv *, jobject, jlong);

/*
 * Class:     com_pzque_sparkdl_saoclib_nativeapi_NDRangeKernel__
 * Method:    call
 * Signature: (J[Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_com_pzque_sparkdl_saoclib_nativeapi_NDRangeKernel_00024_call
        (JNIEnv *, jobject, jlong, jlongArray, jlongArray, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
