/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_pzque_sparkdl_saoclib_ClImage__ */

#ifndef _Included_com_pzque_sparkdl_saoclib_ClImage__
#define _Included_com_pzque_sparkdl_saoclib_ClImage__
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_pzque_sparkdl_saoclib_ClImage__
 * Method:    newInstance
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_pzque_sparkdl_saoclib_ClImage_00024_newInstance
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_pzque_sparkdl_saoclib_ClImage__
 * Method:    destroyInstance
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_pzque_sparkdl_saoclib_ClImage_00024_destroyInstance
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_pzque_sparkdl_saoclib_ClImage__
 * Method:    deployImage
 * Signature: (J[J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_pzque_sparkdl_saoclib_ClImage_00024_deployImage
  (JNIEnv *, jobject, jlong, jlongArray);

#ifdef __cplusplus
}
#endif
#endif
