/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_pzque_sparkdl_saoclib_KernelArgLimit__ */

#ifndef _Included_com_pzque_sparkdl_saoclib_KernelArgLimit__
#define _Included_com_pzque_sparkdl_saoclib_KernelArgLimit__
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_pzque_sparkdl_saoclib_KernelArgLimit__
 * Method:    destroyInstance
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_pzque_sparkdl_saoclib_KernelArgLimit_00024_destroyInstance
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_pzque_sparkdl_saoclib_KernelArgLimit__
 * Method:    void_output
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_pzque_sparkdl_saoclib_KernelArgLimit_00024_void_1output
  (JNIEnv *, jobject);

/*
 * Class:     com_pzque_sparkdl_saoclib_KernelArgLimit__
 * Method:    c_int_input
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_pzque_sparkdl_saoclib_KernelArgLimit_00024_c_1int_1input
  (JNIEnv *, jobject);

/*
 * Class:     com_pzque_sparkdl_saoclib_KernelArgLimit__
 * Method:    c_int_output
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_pzque_sparkdl_saoclib_KernelArgLimit_00024_c_1int_1output
  (JNIEnv *, jobject);

/*
 * Class:     com_pzque_sparkdl_saoclib_KernelArgLimit__
 * Method:    c_float_input
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_pzque_sparkdl_saoclib_KernelArgLimit_00024_c_1float_1input
  (JNIEnv *, jobject);

/*
 * Class:     com_pzque_sparkdl_saoclib_KernelArgLimit__
 * Method:    c_float_output
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_pzque_sparkdl_saoclib_KernelArgLimit_00024_c_1float_1output
  (JNIEnv *, jobject);

/*
 * Class:     com_pzque_sparkdl_saoclib_KernelArgLimit__
 * Method:    c_double_input
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_pzque_sparkdl_saoclib_KernelArgLimit_00024_c_1double_1input
  (JNIEnv *, jobject);

/*
 * Class:     com_pzque_sparkdl_saoclib_KernelArgLimit__
 * Method:    c_double_output
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_pzque_sparkdl_saoclib_KernelArgLimit_00024_c_1double_1output
  (JNIEnv *, jobject);

/*
 * Class:     com_pzque_sparkdl_saoclib_KernelArgLimit__
 * Method:    c_int_array_input
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_pzque_sparkdl_saoclib_KernelArgLimit_00024_c_1int_1array_1input
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_pzque_sparkdl_saoclib_KernelArgLimit__
 * Method:    c_int_array_output
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_pzque_sparkdl_saoclib_KernelArgLimit_00024_c_1int_1array_1output
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_pzque_sparkdl_saoclib_KernelArgLimit__
 * Method:    c_float_array_input
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_pzque_sparkdl_saoclib_KernelArgLimit_00024_c_1float_1array_1input
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_pzque_sparkdl_saoclib_KernelArgLimit__
 * Method:    c_float_array_output
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_pzque_sparkdl_saoclib_KernelArgLimit_00024_c_1float_1array_1output
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_pzque_sparkdl_saoclib_KernelArgLimit__
 * Method:    c_double_array_input
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_pzque_sparkdl_saoclib_KernelArgLimit_00024_c_1double_1array_1input
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_pzque_sparkdl_saoclib_KernelArgLimit__
 * Method:    c_double_array_output
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_pzque_sparkdl_saoclib_KernelArgLimit_00024_c_1double_1array_1output
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
