/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_pzque_sparkdl_saoclib_NativeSize__ */

#ifndef _Included_com_pzque_sparkdl_saoclib_NativeSize__
#define _Included_com_pzque_sparkdl_saoclib_NativeSize__
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_pzque_sparkdl_saoclib_NativeSize__
 * Method:    sizeof_c_int
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_pzque_sparkdl_saoclib_NativeSize_00024_sizeof_1c_1int
  (JNIEnv *, jobject);

/*
 * Class:     com_pzque_sparkdl_saoclib_NativeSize__
 * Method:    sizeof_c_unsigned
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_pzque_sparkdl_saoclib_NativeSize_00024_sizeof_1c_1unsigned
  (JNIEnv *, jobject);

/*
 * Class:     com_pzque_sparkdl_saoclib_NativeSize__
 * Method:    sizeof_c_float
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_pzque_sparkdl_saoclib_NativeSize_00024_sizeof_1c_1float
  (JNIEnv *, jobject);

/*
 * Class:     com_pzque_sparkdl_saoclib_NativeSize__
 * Method:    sizeof_c_double
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_pzque_sparkdl_saoclib_NativeSize_00024_sizeof_1c_1double
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
