/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_pzque_sparkdl_saoclib_nativeapi_NativeTypeID__ */

#ifndef _Included_com_pzque_sparkdl_saoclib_nativeapi_NativeTypeID__
#define _Included_com_pzque_sparkdl_saoclib_nativeapi_NativeTypeID__
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_pzque_sparkdl_saoclib_nativeapi_NativeTypeID__
 * Method:    id_c_void
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_pzque_sparkdl_saoclib_nativeapi_NativeTypeID_00024_id_1c_1void
  (JNIEnv *, jobject);

/*
 * Class:     com_pzque_sparkdl_saoclib_nativeapi_NativeTypeID__
 * Method:    id_c_byte
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_pzque_sparkdl_saoclib_nativeapi_NativeTypeID_00024_id_1c_1byte
  (JNIEnv *, jobject);

/*
 * Class:     com_pzque_sparkdl_saoclib_nativeapi_NativeTypeID__
 * Method:    id_c_short
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_pzque_sparkdl_saoclib_nativeapi_NativeTypeID_00024_id_1c_1short
  (JNIEnv *, jobject);

/*
 * Class:     com_pzque_sparkdl_saoclib_nativeapi_NativeTypeID__
 * Method:    id_c_int
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_pzque_sparkdl_saoclib_nativeapi_NativeTypeID_00024_id_1c_1int
  (JNIEnv *, jobject);

/*
 * Class:     com_pzque_sparkdl_saoclib_nativeapi_NativeTypeID__
 * Method:    id_c_long
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_pzque_sparkdl_saoclib_nativeapi_NativeTypeID_00024_id_1c_1long
  (JNIEnv *, jobject);

/*
 * Class:     com_pzque_sparkdl_saoclib_nativeapi_NativeTypeID__
 * Method:    id_c_float
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_pzque_sparkdl_saoclib_nativeapi_NativeTypeID_00024_id_1c_1float
  (JNIEnv *, jobject);

/*
 * Class:     com_pzque_sparkdl_saoclib_nativeapi_NativeTypeID__
 * Method:    id_c_double
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_pzque_sparkdl_saoclib_nativeapi_NativeTypeID_00024_id_1c_1double
  (JNIEnv *, jobject);

/*
 * Class:     com_pzque_sparkdl_saoclib_nativeapi_NativeTypeID__
 * Method:    id_c_array
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_pzque_sparkdl_saoclib_nativeapi_NativeTypeID_00024_id_1c_1array
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
