/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_pzque_sparkdl_saoclib_FImage */

#ifndef _Included_com_pzque_sparkdl_saoclib_FImage
#define _Included_com_pzque_sparkdl_saoclib_FImage
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
