/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_pzque_sparkdl_saoclib_FImage__ */

#ifndef _Included_com_pzque_sparkdl_saoclib_FImage__
#define _Included_com_pzque_sparkdl_saoclib_FImage__
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_pzque_sparkdl_saoclib_FImage__
 * Method:    newFImage
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_pzque_sparkdl_saoclib_FImage_00024_newFImage
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_pzque_sparkdl_saoclib_FImage__
 * Method:    getNumDevices
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_pzque_sparkdl_saoclib_FImage_00024_getNumDevices
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_pzque_sparkdl_saoclib_FImage__
 * Method:    initOpenCL
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_pzque_sparkdl_saoclib_FImage_00024_initOpenCL
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_pzque_sparkdl_saoclib_FImage__
 * Method:    disposeInternal
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_pzque_sparkdl_saoclib_FImage_00024_disposeInternal
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
