/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_pzque_sparkdl_saoclib_FEnv__ */

#ifndef _Included_com_pzque_sparkdl_saoclib_FEnv__
#define _Included_com_pzque_sparkdl_saoclib_FEnv__
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_pzque_sparkdl_saoclib_FEnv__
 * Method:    newInstance
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_pzque_sparkdl_saoclib_FEnv_00024_newInstance
  (JNIEnv *, jobject);

/*
 * Class:     com_pzque_sparkdl_saoclib_FEnv__
 * Method:    destroyInstance
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_pzque_sparkdl_saoclib_FEnv_00024_destroyInstance
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_pzque_sparkdl_saoclib_FEnv__
 * Method:    initOpenCL
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_pzque_sparkdl_saoclib_FEnv_00024_initOpenCL
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_pzque_sparkdl_saoclib_FEnv__
 * Method:    getNumDevices
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_pzque_sparkdl_saoclib_FEnv_00024_getNumDevices
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_pzque_sparkdl_saoclib_FEnv__
 * Method:    getDeviceIdList
 * Signature: (J)[J
 */
JNIEXPORT jlongArray JNICALL Java_com_pzque_sparkdl_saoclib_FEnv_00024_getDeviceIdList
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_pzque_sparkdl_saoclib_FEnv__
 * Method:    getDeviceId
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_com_pzque_sparkdl_saoclib_FEnv_00024_getDeviceId
  (JNIEnv *, jobject, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
