/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_pzque_sparkdl_saoclib_nativeapi_KernelArgModeID__ */

#ifndef _Included_com_pzque_sparkdl_saoclib_nativeapi_KernelArgModeID__
#define _Included_com_pzque_sparkdl_saoclib_nativeapi_KernelArgModeID__
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_pzque_sparkdl_saoclib_nativeapi_KernelArgModeID__
 * Method:    id_mode_input
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_pzque_sparkdl_saoclib_nativeapi_KernelArgModeID_00024_id_1mode_1input
  (JNIEnv *, jobject);

/*
 * Class:     com_pzque_sparkdl_saoclib_nativeapi_KernelArgModeID__
 * Method:    id_mode_output
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_pzque_sparkdl_saoclib_nativeapi_KernelArgModeID_00024_id_1mode_1output
  (JNIEnv *, jobject);

/*
 * Class:     com_pzque_sparkdl_saoclib_nativeapi_KernelArgModeID__
 * Method:    id_mode_input_output
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_pzque_sparkdl_saoclib_nativeapi_KernelArgModeID_00024_id_1mode_1input_1output
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
